defaults:
  - _self_
  - /cluster: local
  - /algorithm: dqn
  - /environment: cc_cartpole
  - search_space: dqn
  - override hydra/sweeper: HyperPBT

load: false
save: false
reward_curves: false

hydra:
  sweeper:
    budget: 800_000
    budget_variable: autorl.n_total_timesteps
    loading_variable: load
    saving_variable: save
    search_space: ${search_space}
    sweeper_kwargs:
      optimizer_kwargs:
        population_size: 8
        config_interval: 1e5
        seed: ${pbt_seed}
      checkpoint_tf: false
      load_tf: false
  run:
    dir: results/pbt/${pbt_seed}/${algorithm}_${autorl.env_name}/${autorl.seed}
  sweep:
    dir: results/pbt/${pbt_seed}/${algorithm}_${autorl.env_name}/${autorl.seed}
  job:
    chdir: true

pbt_seed: 42
jax_enable_x64: false

autorl:
  seed: 42
  env_framework: ${environment.framework}
  env_name: ${environment.name}
  env_kwargs: ${environment.kwargs}
  n_envs: ${environment.n_envs}
  algorithm: ${algorithm}
  cnn_policy: ${environment.cnn_policy}
  n_total_timesteps: ${environment.n_total_timesteps}
  checkpoint: []
  checkpoint_name: "default_checkpoint"
  checkpoint_dir: "/tmp"
  objectives: ["reward_mean"]
  optimize_objectives: "lower"
  state_features: []
  n_steps: 10
  n_eval_steps: 100
  n_eval_episodes: 10
