# @package _global_
algorithm: sac
hp_config:
  alpha: 1.0
  alpha_auto: true
  buffer_alpha: 0.9
  buffer_batch_size: 256
  buffer_beta: 0.9
  buffer_epsilon: 1.0e-05
  buffer_prio_sampling: false
  buffer_size: 1000000
  gamma: 0.99
  gradient_steps: 1
  learning_rate: 0.0003
  learning_starts: 100
  normalize_observations: false
  target_update_interval: 1
  tau: 0.005
  train_freq: 1
  use_target_network: true
nas_config:
  activation: tanh
  hidden_size: 256
