seed: 0
hyperparameters:
  hp_config.buffer_prio_sampling:
    type: categorical
    choices: [True, False]
  hp_config.buffer_alpha:
    type: uniform_float
    upper: 1.0
    lower: 0.01
    log: false
  hp_config.buffer_beta:
    type: uniform_float
    upper: 1.0
    lower: 0.01
    log: false
  hp_config.buffer_epsilon:
    type: uniform_float
    upper: 1e-3
    lower: 1e-7
    default: 1e-6
    log: true
  hp_config.buffer_batch_size:
    type: categorical
    choices: [16, 32, 64]
  hp_config.buffer_size:
    type: uniform_int
    upper: 1000000
    lower: 1024
    log: false
  hp_config.initial_epsilon:
    type: uniform_float
    upper: 1.0
    lower: 0.5
    log: false
  hp_config.target_epsilon:
    type: uniform_float
    upper: 0.2
    lower: 0.001
    log: false
  hp_config.learning_rate:
    type: uniform_float
    upper: 0.1
    lower: 1.0e-06
    log: true
  hp_config.learning_starts:
    type: uniform_int
    upper: 32768
    lower: 1024
    log: false
  hp_config.use_target_network:
    type: categorical
    choices: [True, False]
  hp_config.target_update_interval:
    type: uniform_int
    upper: 2000
    lower: 1
    log: false
conditions:
  - child: hp_config.target_update_interval
    parent: hp_config.use_target_network
    value: true
    type: EQ
  - child: hp_config.buffer_epsilon
    parent: hp_config.buffer_prio_sampling
    value: true
    type: EQ
  - child: hp_config.buffer_alpha
    parent: hp_config.buffer_prio_sampling
    value: true
    type: EQ
  - child: hp_config.buffer_beta
    parent: hp_config.buffer_prio_sampling
    value: true
    type: EQ
