seed: 0
hyperparameters:
  hp_config.buffer_alpha:
    type: uniform_float
    upper: 1.0
    lower: 0.01
    default: 0.9
    log: false
  hp_config.buffer_batch_size:
    type: categorical
    choices:
      - 32
      - 64
      - 128
    default: 128
  hp_config.buffer_beta:
    type: uniform_float
    upper: 1.0
    lower: 0.01
    default: 0.9
    log: false
  hp_config.buffer_epsilon:
    type: uniform_float
    upper: 1e-3
    lower: 1e-7
    default: 1e-6
    log: true
  hp_config.buffer_prio_sampling:
    type: categorical
    choices:
      - true
      - false
    default: false
  hp_config.initial_epsilon:
    type: uniform_float
    upper: 1.0
    lower: 0.5
    default: 1.0
    log: false
  hp_config.target_epsilon:
    type: uniform_float
    upper: 0.2
    lower: 0.001
    default: 0.05
    log: false
  hp_config.learning_rate:
    type: uniform_float
    upper: 0.1
    lower: 1.0e-06
    default: 0.0003
    log: true
  hp_config.learning_starts:
    type: uniform_int
    upper: 2048
    lower: 0
    default: 128
    log: false
  hp_config.target_update_interval:
    type: uniform_int
    upper: 100
    lower: 1
    default: 10
    log: false
