# @package _global_
defaults:
  - override hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: ai
    cpus_per_task: 1
    gres: null
    timeout_min: 5
    mem_gb: 1
    setup:
      - export JAX_PLATFORM_NAME=cpu
