defaults:
  - _self_
  - /environment: cc_cartpole

hydra:
  run:
    dir: results/${algorithm}_${environment.name}/${autorl.seed}
  sweep:
    dir: results/${algorithm}_${environment.name}/${autorl.seed}
  job:
    chdir: true

jax_enable_x64: false
load_checkpoint: ""
algorithm: dqn

autorl:
  seed: 42
  env_framework: ${environment.framework}
  env_name: ${environment.name}
  env_kwargs: ${environment.kwargs}
  eval_env_kwargs: ${environment.eval_kwargs}
  n_envs: ${environment.n_envs}
  algorithm: ${algorithm}
  cnn_policy: ${environment.cnn_policy}
  nas_config: ${nas_config}
  n_total_timesteps: 1e4
  checkpoint: []
  checkpoint_name: "default_checkpoint"
  checkpoint_dir: "/tmp"
  state_features: []
  objectives: ["reward_mean"]
  optimize_objectives: "upper"
  n_steps: 10
  n_eval_steps: 100
  n_eval_episodes: 10


hp_config:
  buffer_prio_sampling: false
  buffer_alpha: 0.9
  buffer_beta: 0.9
  buffer_epsilon: 0.001
  buffer_batch_size: 16
  buffer_size: 1000000
  initial_epsilon: 0.9
  target_epsilon: 0.9
  gamma: 0.99
  gradient_steps: 1
  learning_rate: 0.0003
  learning_starts: 128
  normalize_observations: false
  train_freq: 4
  use_target_network: true
  target_update_interval: 1000
  tau: 1.0

nas_config:
  activation: tanh
  hidden_size: 64