# @package _global_
defaults:
  - override /environment: atari_pong    
  - override /algorithm: dqn    

# https://huggingface.co/sb3/dqn-PongNoFrameskip-v4
environment:
  n_envs: 8
  n_total_timesteps: 10000000

hp_config:
  buffer_batch_size: 32
  buffer_size: 10000
  target_epsilon: 0.01
  gradient_steps: 2
  learning_rate: 0.0001
  learning_starts: 100000
  target_update_interval: 1000
  train_freq: 1
  normalize_observations: False

nas_config:
  activation: relu
  hidden_size: 512
