# @package _global_
defaults:
  - override /environment: atari_this_game
  - override /algorithm: ppo    

# https://huggingface.co/sb3/ppo-PongNoFrameskip-v4
environment:
  n_envs: 8
  n_total_timesteps: 10000000

hp_config:
  minibatch_size: 256
  clip_eps: 0.1
  ent_coef: 0.01
  learning_rate: 2.5e-4
  update_epochs: 4
  n_steps: 128
  vf_coef: 0.5
  normalize_observations: False

nas_config:
  activation: relu
  hidden_size: 512
