# @package _global_
defaults:
  - override /environment: box2d_bipedal_walker
  - override /algorithm: ppo

environment:
  n_total_timesteps: 1000000
  n_envs: 8
  kwargs:
    max_episode_steps: 1600
  eval_kwargs:
    max_episode_steps: 1600

hp_config:
  clip_eps: 0.18
  gamma: 0.99
  ent_coef: 0.0
  learning_rate: 0.0003
  minibatch_size: 64
  gae_lambda: 0.95
  update_epochs: 10
  n_steps: 512
  normalize_advantage: False
  normalize_observations: True

nas_config:
  activation: relu
  hidden_size: 128
